### ISSUE TITLE
set stdio encoding to utf-8 on windows

### ISSUE THREAD

**Issue by Heather** [jaspervdj/stylish-haskell#108]
related issue: https://github.com/atom-haskell/ide-haskell-cabal/issues/11#issuecomment-222075876

when I run `chcp 65001` it helps but it seems like it could break integration with other things

is it possible to set stdio encoding to utf-8 on windows?

**Comment by jaspervdj** [comment]
Yeah, I agree that this is a good idea, since it seems UTF-8 is at least how GHC reads files ([source](https://prime.haskell.org/wiki/UnicodeInHaskellSource)). We can do this on all platforms and allow users to disable it with a command-line option.

**Comment by Heather** [comment]
but just adding

``` haskell
        hSetEncoding stdout utf8
        readUTF8File fileName >>= putStr
```

doesn't help with atom, cc @lierdakil

**Comment by lierdakil** [comment]
That's probably because ide-haskell uses stylish-haskell as filter, i.e. source is passed on stdin instead of file. Try to `hSetEncoding stdin utf8`.

**Comment by Heather** [comment]
@lierdakil no effect and no error messages

**Comment by jaspervdj** [comment]
Another approach could be using the `bytestring` library, reading `stdin` as raw `ByteString` and using `T.unpack . Data.Text.Encoding.decodeUtf8` to convert it into a `String`. It's a bit more hassle but it would do the job, I think.

**Comment by lierdakil** [comment]
@Heather, I think you might be hacking on the wrong part of stylish-haskell there... lines 52-55 of `src/Main.hs` have to do with dumping default config, not actual "stylishing".

You might want to do this in `main` before call to `stylishHaskell` (should work) or in `file` (might work)

Minimal example:
```haskell
main :: IO ()
main = do
    mapM_ (`hSetEncoding` utf8) [stdin, stdout]
    cmdArgs stylishArgs >>= stylishHaskell
```

**Comment by Heather** [comment]
@jaspervdj seems like helped https://github.com/jaspervdj/stylish-haskell/pull/109

**Comment by Heather** [comment]
@jaspervdj btw, it doesn't work with CPP things alike `#if MIN_VERSION_Win32(2,3,1)` - is it known issue?

**Comment by jaspervdj** [comment]
Yes @Heather, CPP is impossible to parse in some cases, so stylish-haskell doesn't try.

**Comment by jaspervdj** [comment]
@Heather I've added an `--utf8` flag which should do the job in 90f18cb6899aaddcbce4b1afeb0e1ca5c3102fcf, which is on the `master` branch. Could you try that out on Windows? I hope there's some way to tell atom that it should use the `--utf8` flag.

**Comment by lierdakil** [comment]
That would be my job... Sigh. I'll have to check version of stylish-haskell
now as well.
1 июня 2016 г. 9:41 PM пользователь "Jasper Van der Jeugt" <
notifications@github.com> написал:

**Comment by Heather** [comment]
@jaspervdj sure I can test it some later, it doesn't use change I used to add so result could be different
``` haskell
+readUTF8File :: FilePath -> IO String
 +readUTF8File fp = do
 +    content <- B.readFile fp
 +    let utf = decodeUtf8 content
 +    return (T.unpack utf)
```

**Comment by jaspervdj-luminal** [comment]
@lierdakil oh, in that case I can make it the default. It shouldn't hurt.

@heather That code is not used if you're just using `stylish-haskell` as a unix filter (which I believe Atom is doing), so it should not matter.

**Comment by lierdakil** [comment]
If you could make it default, that would be great. Thanks.
1 июня 2016 г. 11:02 PM пользователь "Jasper Van der Jeugt" <
notifications@github.com> написал:

**Comment by jaspervdj** [comment]
I've uploaded `stylish-haskell-0.5.17.0`, which sets stdin/stdout encoding to UTF-8 by default. That should fix this issue. Feel free to re-open if it doesn't.
