### ISSUE TITLE
Allow parsing syntax-related language extensions when pragma is absent

### ISSUE THREAD

**Issue by siddharthist** [jaspervdj/stylish-haskell#117]
I got a parse failure on a file with `UnicodeSyntax`, but without a `UnicodeSyntax` LANGUAGE pragma. The language extension is instead enabled in my cabal file. 
```
$ stylish-haskell test/Parse.hs | head -n 24
Language.Haskell.Stylish.Parse.parseModule: could not parse test/Parse.hs: ParseFailed (SrcLo
c "<unknown>.hs" 22 1) "TemplateHaskell language extension is not enabled. Please add {-# LAN
GUAGE TemplateHaskell #-} pragma at the top of your module."                                
module Parse where

import           ClassyPrelude
import           Test.Tasty
import           Test.Tasty.HUnit
-- testing dependencies
import qualified Data.Either                        as Either
import Unicode.Prelude
import           Text.Megaparsec (parse, ParseError)
import Text.Megaparsec.Error (Dec)
import Text.Megaparsec.String (Parser)
import           UnicodeData.Types                  (BidiClass (..),
                                                     GeneralCategory (..),
                                                     NumericType (..),
                                                     RawChar (..))
import           Util
-- modules we will test
import           UnicodeData.Parse

-- run a parser with no name in the identity monad
runParser ∷ Parser a → String → Either (ParseError Char Dec) a
runParser = flip parse "test/Parse.hs"

isLeft ∷ Either.Either a b → Bool

```
If I use a pragma at the top of the file, it works just fine:
```
UnicodeData ➤ stylish-haskell test/Parse.hs | head -n 24
{-# LANGUAGE UnicodeSyntax #-}
module Parse where

import           ClassyPrelude
import           Test.Tasty
import           Test.Tasty.HUnit
-- testing dependencies
import qualified Data.Either            as Either
import           Text.Megaparsec        (ParseError, parse)
import           Text.Megaparsec.Error  (Dec)
import           Text.Megaparsec.String (Parser)
import           Unicode.Prelude
import           UnicodeData.Types      (BidiClass (..), GeneralCategory (..),
                                         NumericType (..), RawChar (..))
import           Util
-- modules we will test
import           UnicodeData.Parse

-- run a parser with no name in the identity monad
runParser ∷ Parser a → String → Either (ParseError Char Dec) a
runParser = flip parse "test/Parse.hs"

isLeft ∷ Either.Either a b → Bool
isLeft = Either.either (\_ → True) (\_ → False)
```
Is there some switch that gets flipped when stylish-haskell encounters the pragma to let it know it's parsing a `UnicodeSyntax` file? Could it also detect it from the cabal file? Or just always support parsing `UnicodeSyntax`? If you can point me to a location in the code to start digging, I can give it a shot.

**Comment by jaspervdj** [comment]
Parsing language extensions from the cabal file is a bit outside of the scope of this project, in my opinion.  You can add them `language_extensions` in your `.stylish-haskell.yaml` configuration file, if you want to.  However, I always recommend putting all the extensions on top of the file.  That way the file is more "portable" and external tools (like `stylish-haskell`) can read it more easily.

**Comment by siddharthist** [comment]
@jaspervdj I agree that parsing the cabal file is probably not the best solution. 

Is there a reason not to just always accept/parse both `UnicodeSyntax` and non-`UnicodeSyntax` source?

While we could expect everyone to put the language extensions at the top of every file, that places a burden on users of `stylish-haskell` that isn't present in other tooling.

**Comment by jaspervdj** [comment]
Hmm, yeah, I suppose we could have a whitelist of "safe" extensions that we can always allow. `UnicodeSyntax` would definitely be part of that.

**Comment by siddharthist** [comment]
@jaspervdj I changed the issue title to match. And because I just ran into this one:
```
$ stylish-haskell test/Parse.hs| head -n 10
Language.Haskell.Stylish.Parse.parseModule: could not parse test/Parse.hs: ParseFailed (SrcLo
c "<unknown>.hs" 26 1) "StandaloneDeriving language extension is not enabled. Please add {-# 
LANGUAGE StandaloneDeriving #-} pragma at the top of your module."                          
```
I'd say we should add `StandaloneDeriving` to the list :smile: 

I think that ultimately, `stylish-haskell` can't really have any knowledge about which language extensions are currently in use, as they could even be enabled at compile-time on the command line. As the project doesn't want to (and shouldn't!) get into the business of figuring that out, it should be as flexible as possible in parsing source.

**Comment by jaspervdj** [comment]
Yes, agreed.  Would you be willing to implement this?  I would be happy to assist where you need help.

**Comment by siddharthist** [comment]
@jaspervdj I'll see what I can do!
