### ISSUE TITLE
Parse error on empty GADT

### ISSUE THREAD

**Issue by cotrone** [jaspervdj/stylish-haskell#122]
When running stylish-haskell on GADT with no constructors fails with a parse error:

```
ParseFailed (SrcLoc "<unknown>.hs" 4 1) "Parse error: virtual }"
```

The input was

``` haskell
{-# LANGUAGE GADTs #-}

data SomeGADT a where
```

It succeeds if the where clause is removed

``` haskell
{-# LANGUAGE GADTs #-}

data SomeGADT a
```

but the where clause is valid. Unsure where the code for the parser is is but I'll look in to finding it to see if I can fix it if it should be fixed.

**Comment by geraldus** [comment]
Can you try to enable GADT support in config file, e.g.:
```
# write defaults
stylish-haskell -d > .stylish-haskell.yaml
```
```
# edit .stylish-haskell.yaml
language_extensions:
  - GADT
```

**Comment by neongreen** [comment]
@geraldus I just tried your suggestion and it doesn't work either.

**Comment by neongreen** [comment]
Filed a haskell-src-exts issue: https://github.com/haskell-suite/haskell-src-exts/issues/358

**Comment by geraldus** [comment]
@neongreen by the way, I guess my example is a bit wrong, it should look like

```yaml
# edit .stylish-haskell.yaml
language_extensions:
- GADTs # no extra spaces at line start
```

**Comment by neongreen** [comment]
It doesn't matter for YAML.

**Comment by Ailrun** [comment]
Maybe it's resolved now?

**Comment by cotrone** [comment]
Just tested with stylish-haskell 0.12.2.0. Looks like it's fixed!
