### ISSUE TITLE
Parse fails on <b

### ISSUE THREAD

**Issue by sweatybridge** [jaspervdj/stylish-haskell#130]
Fails
```
smaller a b  = a <b
```

Succeeds
```
smaller a b = a < b
```

**Comment by jaspervdj** [comment]
Confirmed.  I've opened a proxy issue for `haskell-src-exts` (the parser) here: https://github.com/haskell-suite/haskell-src-exts/issues/325

**Comment by jaspervdj** [comment]
This is because we have `XmlSyntax` as whitelisted extension.  Whitelisting that extension was a mistake, I will revert it.
