### ISSUE TITLE
comments on imports disappear

### ISSUE THREAD

**Issue by willtim** [jaspervdj/stylish-haskell#131]
stylish is great, but I feel this is not a small issue, as it means stylish is essentially a lossy transform.
e.g.
import Foo.Bar.Baz -- this comment won't survive!

**Comment by osa1** [comment]
:+1: came here to report this, I can't document my imports anymore!

**Comment by siddharthist** [comment]
Duplicate of #39

**Comment by neongreen** [comment]
Closing in favor of #39.
