### ISSUE TITLE
fails to parse nested let-bound do-blocks

### ISSUE THREAD

**Issue by willtim** [jaspervdj/stylish-haskell#132]
This isn't my preferred style, but I do see it occurring frequently among my colleagues.
For example:

```
main = do
  let body = do
    e <- readChan chan
    case e of
      Foo -> return True
      Bar -> return False
  finally (endless body) (close chan)
```

Fails to parse with: "Parse error: Last statement in a do-block must be an expression"

**Comment by neongreen** [comment]
It can't be parsed by GHC either:

```
main = do
  let body = do
    e <- readChan chan
    case e of
      Foo -> return True
      Bar -> return False
  finally (endless body) (close chan)
```

```
h.hs:3:5: error: parse error on input ‘e’
```

That's because body of `body` has to be indented further than `b` in `let body`. If you fix it, stylish-haskell works correctly.

**Comment by neongreen** [comment]
(If you have a different example that doesn't work, please reopen the issue.)
