### ISSUE TITLE
stylish-haskell breaks alignments inside a function using guards.

### ISSUE THREAD

**Issue by vonavi** [jaspervdj/stylish-haskell#134]
Hello, guys!
If I have such a function

``` haskell
isPositive n | n > 0 = True
isPositive _         = False
```

then SH breaks its alignments in the following way:

``` haskell
isPositive n | n > 0 = True
isPositive _ = False
```

On my mind, the function with guards was treated by SH as a record.

Best regards,
Vladimir.

**Comment by jhmcstanton** [comment]
Looks like this issue can be closed, the alignment remains as expected in the latest version of SH
