### ISSUE TITLE
Pragma removed even when remove_redundant is set to false

### ISSUE THREAD

**Issue by y-usuzumi** [jaspervdj/stylish-haskell#147]
Hi. I have a project where circular imports exist. The solution I have so far is using .hs-boot files and `{-# SOURCE #-}` pragma.

However, stylish-haskell (tried with version 0.6.5.0) removes `{-# SOURCE #-}` pragmas despite `remove_redundant=false` and causes compilation errors.

**Comment by neongreen** [comment]
This has been fixed in https://github.com/jaspervdj/stylish-haskell/pull/143.
