### ISSUE TITLE
Compact pragma style wraps at an awkward place

### ISSUE THREAD

**Issue by chris-martin** [jaspervdj/stylish-haskell#154]
The `language_pragmas` step with `style: compact` and `columns: 80` produces this:

```haskell
{-# LANGUAGE DefaultSignatures, FlexibleInstances, LambdaCase, TypeApplications
             #-}
```

I think this looks a bit weird. If there is no pragma to place on the last line, could we push the last pragma down onto it? This would be nicer:

```haskell
{-# LANGUAGE DefaultSignatures, FlexibleInstances, LambdaCase,
             TypeApplications #-}
```

**Comment by neongreen** [comment]
It should be easy to implement by attaching `#-}` to the last pragma instead of treating it as a separate token. I'll make a PR tomorrow.
