### ISSUE TITLE
Fail on parsing multi line strings

### ISSUE THREAD

**Issue by geraldus** [jaspervdj/stylish-haskell#157]
My module have multi line string, e.g.:
```
longString :: String
longString = "This is \
    my long string"
```

Stylish Haskell claims on me with error:
```
Language.Haskell.Stylish.Parse.parseModule: could not parse <unknown>: ParseFailed (SrcLoc "<unknown>.hs" 23 3) "Illegal character in string gap"
```

I wasn't able to find a solution.  Please help.

**Comment by neongreen** [comment]
You forgot another `\`:

```
longString :: String
longString = "This is \
    \my long string"
```

This is parsed correctly by stylish-haskell and GHC.

**Comment by geraldus** [comment]
Indeed, you're right!  I can't understand how my code works.
