### ISSUE TITLE
Fail on parsing the #| operator when not preceded by a space

### ISSUE THREAD

**Issue by neongreen** [jaspervdj/stylish-haskell#159]
```
x = a#|b
```

The file above causes the following parsing error:

```
Language.Haskell.Stylish.Parse.parseModule: could not parse /tmp/x.hs: ParseFailed (SrcLoc "<unknown>.hs" 1 7) "Parse error: |"
```

When I add spaces, everything parses fine. haskell-src-exts can parse it fine as well:

```
Prelude Language.Haskell.Exts> fmap (const ()) (parseExpWithMode defaultParseMode "a#|b")
ParseOk ()
```

**Comment by neongreen** [comment]
Ah, it's probably because `MagicHash` is enabled by default: https://github.com/jaspervdj/stylish-haskell/blob/master/lib/Language/Haskell/Stylish/Parse.hs#L27. Is there any way to disable it in config? Or perhaps even remove it from extensions that are enabled by default?

**Comment by jaspervdj** [comment]
Oh!  The default extensions are supposed to be a set of extensions that can "always" be enabled without affecting any code.  This ticket proves that's not the case for `MagicHash`, so we must remove it.

**Comment by neongreen** [comment]
Should I make a PR or is the overhead not worth it?

**Comment by jaspervdj** [comment]
Feel free to make a PR.  It would be great if you could also include a test case to `tests/Language/Haskell/Stylish/Parse/Tests.hs` to demonstrate the behavior, and so that we don't enable it again accidentally.
