### ISSUE TITLE
Pad only the qualified column

### ISSUE THREAD

**Issue by alexkazik** [jaspervdj/stylish-haskell#172]
I'd like the option to only pad the qualified column, that way the right padding will not change every time a new (longer) import is added and all imports are changed. That leads into merge conflicts with multiple users working on it.

Attached is my try.
[pad-only-qualified.patch.txt](https://github.com/jaspervdj/stylish-haskell/files/1067930/pad-only-qualified.patch.txt)

**Comment by jaspervdj** [comment]
This is done in #142

**Comment by jaspervdj** [comment]
It was renamed to `pad_module_names`.  Thanks for the patch though!

**Comment by akazik** [comment]
Thanks for the new feature and glad I could help.
