### ISSUE TITLE
Doesn't work with DerivingStrategies

### ISSUE THREAD

**Issue by ChShersh** [jaspervdj/stylish-haskell#186]
GHC 8.2.1 introduced `-XDerivingStrategies` extension. But `stylish-haskell` fails to parse code which uses this extension, like in example below:

```haskell
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

newtype MyType = MyType Int
    deriving newtype Read
```

and produces the following error:

```
Language.Haskell.Stylish.Parse.parseModule: could not parse Der.hs: ParseFailed (SrcLoc "<unknown>.hs" 5 14) "Parse error: newtype"
```

```bash
$ stylish-haskell --version
stylish-haskell 0.8.1.0
```

**Comment by ChShersh** [comment]
`-XDerivingStrategies` extension is supported in newest `haskell-src-exts-1.20`. I've installed newest `stylish-haskell`:

```shell
$ stylish-haskell --version
stylish-haskell 0.9.0.2
```

But still observing same parsing error.

**Comment by mizunashi-mana** [comment]
Now, `haskell-src-exts-1.20.1` is included in stackage nightly (https://www.stackage.org/nightly-2018-01-26/package/haskell-src-exts-1.20.1).  I resolved this issue by using `nightly-2018-01-26` as the stack resolver.

**Comment by ChShersh** [comment]
@mizunashi-mana Thanks! That resolves issue for me.
