### ISSUE TITLE
BangPatterns pragma gets stripped

### ISSUE THREAD

**Issue by justanotherdot** [jaspervdj/stylish-haskell#189]
Thanks for the awesome work with `stylish-haskell`! Despite alternatives it's still my preferred code format tool for Haskell. 

Running `stylish-haskell 0.6.1.0` on a Haskell file with pragmas seems to strip `BangPatterns` from the file:

```
η cat file.hs
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE BangPatterns #-}

main :: IO ()
main = putStrLn "Not impl."
η cat file.hs | stylish-haskell    
{-# LANGUAGE RecordWildcards #-}

main :: IO ()
main = putStrLn "Not impl."
```

The same result after filtering is present regardless of the position of `BangPatterns` or if mentioned as a list e.g. `{-# LANGUAGE RecordWildCards, BangPatterns #-}`. This doesn't seem to happen if I put enough spaces between the first and second pragma.

Happy to try to take a crack at submitting a PR if this is a confirmed issue and if someone wants to help guide me a bit with what needs to be changed.

**Comment by vimuel** [comment]
Stylish-haskell removes some unused pragmas depending on what's in your config file.

**Comment by justanotherdot** [comment]
Ah of course, sorry about that!

**Comment by ivanperez-keera** [comment]
(Sorry for the comment in a closed question but, why not all?

For example, with the Arrows and BangPatterns extension pragmas and nothing else in the fie, the first is kept and the second is removed.
