### ISSUE TITLE
Add way to quickly get stylish-haskell binaries

### ISSUE THREAD

**Issue by lwm** [jaspervdj/stylish-haskell#192]
Basically https://github.com/ndmitchell/hlint#running-with-continuous-integration. Not a biggie, the install is quite fast, but this would be cool. Mainly because handling installing GHCs on Travis is a bit of a pain. But it'd be faster. I like fast. I use `stylish-haskell` a lot for my CI builds. I can help if this is something that you all think is useful.

**Comment by lwm** [comment]
For example, a 6+ minute `stylish-haskell` build over at https://travis-ci.org/lwm/tasty-discover/jobs/319274882 vs. a 1+ minute build over at https://travis-ci.org/lwm/tasty-discover/jobs/319274881 with the `HLint` binary.

**Comment by jaspervdj** [comment]
That makes sense.  Do you just need linux binaries?

**Comment by jaspervdj** [comment]
We'll need to incorporate the default config file in the executable rather than using cabal's `Data-files`.

**Comment by lwm** [comment]
Cool!

> Do you just need linux binaries?

Yep! That'd be fine for me.

> We'll need to incorporate the default config file in the executable

OK, good to know. 

How to proceed on this one? Not sure what needs to be done.

**Comment by jaspervdj** [comment]
I'll do it, I was in the process of porting things over to CircleCI rather than Travis anyway.  If things work out, releases will be uploaded to the releases page on github.

**Comment by jaspervdj** [comment]
Binaries of releases are now uploaded automatically:

<https://github.com/jaspervdj/stylish-haskell/releases>

**Comment by lwm** [comment]
That is great! Thanks 🍻
