### ISSUE TITLE
stylish-haskell removes ViewPatterns language pragma.

### ISSUE THREAD

**Issue by jezen** [jaspervdj/stylish-haskell#199]
Possibly related to https://github.com/jaspervdj/stylish-haskell/issues/135

Repro steps (in Vim):

1. Select these lines

```
{-# LANGUAGE CPP                   #-}
{-# LANGUAGE ExplicitForAll        #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE NoImplicitPrelude     #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE RankNTypes            #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
{-# LANGUAGE ViewPatterns          #-}
```

2. Run `:'<,'>!stylish-haskell`

3. The ViewPatterns line mysteriously disappears

Running `stylish-haskell 0.8.1.0`, if that matters.

**Comment by ShrykeWindgrace** [comment]
The same problem is present in `0.9.0.2`.

**Comment by jaspervdj** [comment]
I don't really think we can do anything here on the `stylish-haskell` side.  We definitely don't want to run the template Haskell code.

You can, of course, switch of the removal of pragmas completely.  It's the `remove_redundant` setting -- see https://github.com/jaspervdj/stylish-haskell#configuration

**Comment by EncodePanda** [comment]
You've closed it because it is working now?

**Comment by jezen** [comment]
@EncodePanda I closed this because the issue is old, and according to @jaspervdj’s comment above, this won’t/can’t be fixed anyway.

If someone else runs into this, they should still be able to find this issue (I think?). My intention here is to be a _good citizen_ and close old issues where possible. I’m totally fine with keeping it open if anyone sees an actionable way to move forward.
