### ISSUE TITLE
Idea: "Head-only" mode

### ISSUE THREAD

**Issue by chris-martin** [jaspervdj/stylish-haskell#235]
Since there's a lot of stuff that `haskell-src-exts` still can't parse, I've been thinking about workarounds. Here's a trick I used in [another project](https://github.com/typeclasses/hs-nix-modules/blob/5c7cb693c3121b41d46aa28f16209d0b4be1e4f7/hs-nix-modules/executables/hs-nix-modules.hs#L269): instead of parsing the entire [`Module`](https://hackage.haskell.org/package/haskell-src-exts-1.21.0/docs/Language-Haskell-Exts-Syntax.html#t:Module), we only read the [`ModuleHeadAndImports`](https://hackage.haskell.org/package/haskell-src-exts-1.21.0/docs/Language-Haskell-Exts-Parser.html#t:ModuleHeadAndImports). The purpose of that project is just to read the import list, so that suffices. Not everything that stylish-haskell does can be accomplished without parsing the rest of the declarations, but *a lot of* the style rules only affect the language pragmas and imports. So maybe it would be better-than-nothing to be able to run stylish-haskell in "head-only mode", and it would stop parsing at the end of the import declarations and ignore any style rules that affect code below that point? Then those of us who have heavily adopted BlockArguments could start using stylish-haskell again :)

**Comment by kindaro** [comment]
This is so true.

**Comment by chris-martin** [comment]
Note: The specific feature I mentioned, BlockArguments, is supported now - But I still suspect I'll end up wanting this feature at some point again in the future.

**Comment by chris-martin** [comment]
On second thought, this could happen automatically: Parse as much of the file as possible, and run any formatting steps that pertain to the parts of the file that did read successfully.

**Comment by jaspervdj** [comment]
There's a GSoC project this summer to convert `stylish-haskell` to use GHC's parser; so if that is successful it should be easier to stay up to date with newer features.

**Comment by EncodePanda** [comment]
Closing this since 0.12.0.0 we use GHC parser :)
