### ISSUE TITLE
Allow lowecase on language pragmas

### ISSUE THREAD

**Issue by kutyel** [jaspervdj/stylish-haskell#245]
Hi Jasper!

`stylish-haskell` is great, thanks for creating it! 🎉 

Some people (I'm looking at you @serras) prefer to write language pragmas en lowercase, maybe an option to preserve case could be added to:
```
  - language_pragmas:
      preserve_case: true
```

If this is easy enough I can provide a PR! 😄 

Of course this is not critical or anything, I just want to have a stronger argument against convincing Alejandro to use `stylish-haskell` everywhere 😂

**Comment by jaspervdj** [comment]
Thanks @kutyel!  I would be more than happy to have this -- would you be interested in writing the PR?  If you have any questions on where to start, feel free to reach out!
