### ISSUE TITLE
Consider shipping manpage

### ISSUE THREAD

**Issue by spwhitton** [jaspervdj/stylish-haskell#250]
Debian and its derivatives ship a manpage for stylish-haskell which I wrote a while ago and released under the same license as stylish-haskell.

It would be good to upstream that manpage into this repository.

It's here: https://git.spwhitton.name/stylish-haskell/tree/debian/stylish-haskell.1.adoc

I can prepare a PR if you would like.

**Comment by jaspervdj** [comment]
It would be great to have this upstreamed.  Any assistance with a PR is appreciated.
