### ISSUE TITLE
Unable to parse `QuantifiedConstraints` syntax

### ISSUE THREAD

**Issue by fabiomogavero** [jaspervdj/stylish-haskell#252]
GHC 8.6.1 introduced the new QuantifiedConstraints pragma, however, the latest stylish-haskell (ver 0.9.4.4) is unable to parse the associated class assertion syntax. For example, when applied on

class C (a :: *)
class (forall b . C (c b)) => D (c :: * -> *)

the program returns the following error message: Language.Haskell.Stylish.Parse.parseModule: could not parse <unknown>: ParseFailed (SrcLoc "<unknown>.hs" ... ...) "Illegal class assertion".

Thank you very much for your help.

**Comment by EncodePanda** [comment]
Downstream issue on `haskell-src-ext` https://github.com/haskell-suite/haskell-src-exts/issues/433

Low-hanging-fruit once we get support (bump the version up).

**Comment by Matthiasvanderhallen** [comment]
This was fixed by ba5456a9f2c16524ea93c0b038dafc1af8aaaf0e.
