### ISSUE TITLE
Enum formatting

### ISSUE THREAD

**Issue by jaspervdj** [jaspervdj/stylish-haskell#262]
`v0.10.0.0` formats the following:

```
data Tag = Title | Text
```

As:

```
data Tag = Title
    | Text
```

Whereas it should really just stay as-is.  I suspect this may be a problem with the new records formatting?  cc @lukasz-golebiewski @EncodePanda

**Comment by EncodePanda** [comment]
Yeah, we saw that the other day. We will fix that ASAP.
