### ISSUE TITLE
[Feature request] A new pragma style?

### ISSUE THREAD

**Issue by Javran** [jaspervdj/stylish-haskell#278]
Not that new, actually. I've been seeing this style of LANGUAGE pragma for a while and quite like it in comparison to doing `{-# LANGUAGE _ #}` each line,
which should be easily demonstrated by the following example:

```haskell
{-# LANGUAGE
    DataKinds
  , LambdaCase
  , OverloadedStrings
  , RecordWildCards
  , ScopedTypeVariables
  #-}
```

Not sure how should this style be called though, as I'm too lazy to think of one at the moment xD (any suggestion welcomed).
I may tackle this feature myself if no one is strongly against it.

**Comment by EncodePanda** [comment]
@Javran I've accidentally merged you branch to `master` not `main`. Can you reopen the PR from your branch once more?

**Comment by Javran** [comment]
@EncodePanda feel free to merge it back to `main`. I don't deal with any master branch renaming fallout.

**Comment by EncodePanda** [comment]
@jaspervdj fixed it, all is good now https://github.com/jaspervdj/stylish-haskell/commit/77b1caad6d390dcf4a7890b3656cd34954307222
