### ISSUE TITLE
Update dependency to make this compatible with Cabal 3.2

### ISSUE THREAD

**Issue by Ailrun** [jaspervdj/stylish-haskell#290]
Haskell Language Server now introduced stylish-haskell plugin.
Unfortunately, as stylish-haskell restrict the version of Cabal < 3.1, it blocks HLS using Cabal 3.2.0.0. (https://github.com/haskell/haskell-language-server/commit/3436f6afe6113d2e4b278ccbfc30bdd2465255bc#diff-449d2e76ba35ada62ff733845cc009ff)
If it is possible to update dependencies of this project, I think it will be great.

**Comment by EncodePanda** [comment]
Shouldn't really. 
@VBeatrice can you confirm it will not block your work with ghc-lib-parser?

**Comment by VBeatrice** [comment]
@EncodePanda I tried it and it seems to be working fine.

**Comment by Ailrun** [comment]
Fixed in https://github.com/jaspervdj/stylish-haskell/commit/2dd6fbd669e3501d5d4783dfa2d9f9ba3026ea1b.
