### ISSUE TITLE
Language.Haskell.Stylish.Parse.parseModule: could not parse xxx.hs: ParseFailed (SrcLoc "<unknown>.hs" line col) "Parse error: ("

### ISSUE THREAD

**Issue by stephen-smith** [jaspervdj/stylish-haskell#291]
File in question: https://gitlab.com/krakrjak/icfp2020-junkfood/-/blob/8704f0958a118a94ab21538a5ce4ee07b9b74f8f/src/Junkfood/Cmdline.hs

stack "Version 2.3.1 x86_64 hpack-0.33.0" and GHC "The Glorious Glasgow Haskell Compilation System, version 8.8.3" everything builds fine, but stylish can't parse it.

I tried moving things around a bit, but didn't immediately find some changes to work around the parse failure, either.

**Comment by stephen-smith** [comment]
stylish-haskell 0.11.0.0 BTW

**Comment by jaspervdj** [comment]
This should be fixed by #307, please reopen this it’s still an issue?
