### ISSUE TITLE
Fails to parse record punning with a qualified name 

### ISSUE THREAD

**Issue by Mikolaj** [jaspervdj/stylish-haskell#30]
I'm getting

Language.Haskell.Stylish.Parse.parseModule: could not parse <unknown>: ParseFailed (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 353, srcColumn = 35}) "Illegal qualified name"

for the following line of code:

```
cotile = tile {Kind.ospeedup}
```

which otherwise works perfectly in GHC.

**Comment by neongreen** [comment]
Seems to work in latest stylish-haskell. Please reopen the issue if you have an example that doesn't work.
