### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by maksbotan** [jaspervdj/stylish-haskell#310]
Hi @jaspervdj!

This year Hacktoberfest is opt-in for projects: https://twitter.com/hacktoberfest/status/1312221208667185153

Would you be so kind to add `hacktoberfest` topic for this repo?

I already have one PR ready fixing a bug I found with new version ;)

**Comment by jaspervdj** [comment]
Of course, done!  Let me know if you need anything else :-)
