### ISSUE TITLE
Separate lists option do not seem to be respected

### ISSUE THREAD

**Issue by 1Computer1** [jaspervdj/stylish-haskell#320]
Setting `separate_lists: false` still adds the space before the parentheses (irregardless of `ghc_lib_parser`):
```hs
import Data.Monoid (Monoid (..))
```
Also, I suppose this is a feature request, but `module_header` should also have such an option since right now it always adds the space:
```hs
module Foo
    ( Bar (..)
    ) where
```

**Comment by jaspervdj** [comment]
Thanks for reporting!  Should be fixed in the next release.
