### ISSUE TITLE
DataKinds types in GADTs get unticked

### ISSUE THREAD

**Issue by maksbotan** [jaspervdj/stylish-haskell#330]
When `records` step is enabled in the default config with default options:

```haskell
-- before
data Foo a where
  Foo :: Foo 'True

-- after
data Foo a where
  Foo :: Foo True
```

Notice that `'True` in the return type of GADT constructor gets unticked. This triggers a GHC warning and is generally a surprising behavior.

**Comment by jaspervdj** [comment]
Fixed in #332, thanks to @jhmcstanton!
