### ISSUE TITLE
Mentioning HLS plugin in README.markdown

### ISSUE THREAD

**Issue by Ailrun** [jaspervdj/stylish-haskell#347]
For [Haskell Language Server(HLS)](https://github.com/haskell/haskell-language-server) supports stylish-haskell and I believe it is one of the most accessible ways to use style formatters in editors, it would be great if HLS is mentioned somewhere in README.markdown. Maybe as a part of editor support section?

**Comment by jaspervdj** [comment]
Yes, this sounds god -- thanks for bringing it up!  I also think this should be mentioned.  Would you be willing to submit a PR for this?

**Comment by Ailrun** [comment]
Sure, I will.
