### ISSUE TITLE
DataKinds parse error

### ISSUE THREAD

**Issue by wdanilo** [jaspervdj/stylish-haskell#50]
Hello! I'm getting parse error on following Haskell code:

```
[...]
(~^) = defFunction2 (\a b -> get1 (member (Proxy :: Proxy "pow") (get0 a)) b)
[...]
```

Please note, that `:: Proxy "pow"` is a valid Haskell expression if the Proxy was defined in the following way:

```
data Proxy a = Proxy
```

with `-XDataKinds` extension enabled.

The error:

```
Language.Haskell.Stylish.Parse.parseModule: could not parse Std.hs: ParseFailed (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 23, srcColumn = 59}) "Parse error: \"pow\"
```

**Comment by neongreen** [comment]
Works in current version of stylish-haskell.
