### ISSUE TITLE
Doesn't support hash-bangs

### ISSUE THREAD

**Issue by ivan-m** [jaspervdj/stylish-haskell#59]
If I have a Haskell script that starts with "#!/usr/bin/runhaskell" and stylish-haskell is run (automatically by my editor, so I'm not choosing to do this for a simple script ;-) then I get this error:

```
Warning (stylish-haskell): stylish-haskell failed:
    Language.Haskell.Stylish.Parse.parseModule: could not parse <unknown>:
    ParseFailed (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 1, srcColumn
    = 1}) "Parse error: #!/"
```

**Comment by neongreen** [comment]
It works for me on this example:

```
#!/usr/bin/env runhaskell
module Main where
main :: IO ()
main = undefined
```

so I guess this issue can be closed.
