### ISSUE TITLE
Sorting with case insensitivity

### ISSUE THREAD

**Issue by dag** [jaspervdj/stylish-haskell#6]
If I have

``` haskell
import Happstack.Server
import HSP
```

`stylish-haskell` will sort it as

``` haskell
import HSP
import Happstack.Server
```

This is contrary to my expectation and wishes.

**Comment by vlatkoB** [comment]
This is happening again. Can we reopen this issue?

**Comment by EncodePanda** [comment]
Could you please contribute with a test that fails? I will be happy to make that test green :)

**Comment by vlatkoB** [comment]
I tested the above
```haskell
import Happstack.Server
import HSP
```
Or do you mean to make a PR with failed test?

**Comment by EncodePanda** [comment]
> Or do you mean to make a PR with failed test?

Yes, please. That would be most valuable.
Please create a branch where you add a new test that shows the expected behavior. Open a PR. The test will fail, I will make it work :)

**Comment by vlatkoB** [comment]
Created, https://github.com/haskell/stylish-haskell/pull/383

**Comment by vlatkoB** [comment]
@EncodePanda Was the PR good? I see it is still in `1 workflow awaiting approval` status.

**Comment by vlatkoB** [comment]
Thanks. :-)
