### ISSUE TITLE
{-# SOURCE #-} imports are removed

### ISSUE THREAD

**Issue by k-bx** [jaspervdj/stylish-haskell#70]
If you have import like

```
import {-# SOURCE #-} Foo
```

then after haskell-stylish-buffer you will get

```
import Foo
```

**Comment by agrafix** [comment]
Same issue with other comments like the ones required and used by [HTF](https://hackage.haskell.org/package/HTF):

```haskell
{-# OPTIONS_GHC -F -pgmF htfpp #-}
module Main where

import Test.Framework
import Test.Framework.BlackBoxTest
import {-@ HTF_TESTS @-} MyPkg.A
import {-@ HTF_TESTS @-} MyPkg.B

main = htfMain htf_importedTests
```

turns into:

```haskell
{-# OPTIONS_GHC -F -pgmF htfpp #-}
module Main where

import Test.Framework
import Test.Framework.BlackBoxTest
import MyPkg.A
import MyPkg.B

main = htfMain htf_importedTests
```

**Comment by bergmark** [comment]
`{-# SOURCE #-}` is supported as of haskell-src-exts-1.17.0 btw

**Comment by agrafix** [comment]
@jaspervdj should I open a new issue for `{-@ HTF_TESTS @-}` annotations?

**Comment by jaspervdj** [comment]
@agrafix Yes, that would be great!  Maybe there is a way to get all `{- ... -}`-form comments?
