### ISSUE TITLE
False "MultiParamTypeClasses is not enabled"

### ISSUE THREAD

**Issue by k-bx** [jaspervdj/stylish-haskell#71]
If you have type

```
runMySQL :: (MonadIO m, MonadBaseControl IO m) => ConnectInfo -> SqlPersistT (NoLoggingT (ResourceT m)) a -> m a
```

stylish will say something like:
```
Warning (stylish-haskell): stylish-haskell failed:
    Language.Haskell.Stylish.Parse.parseModule: could not parse <unknown>:
    ParseFailed (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 136,
    srcColumn = 51}) "MultiParamTypeClasses is not enabled"
```

But it has nothing to do with multiparamtypeclasses.
// sorry if it's haskell-src-exts issue again

**Comment by phunehehe** [comment]
Looks like this bug should be closed because the right way to do it is to add `{-# LANGUAGE MultiParamTypeClasses #-}`?

**Comment by jaspervdj** [comment]
It's a `haskell-src-exts` issue.

**Comment by phunehehe** [comment]
What I meant is, in the HSE issue, it's concluded this is a GHC bug (the language extension MultiParamTypeClasses is required, not optional, so if you want to use "multi param type classes", you have to enable the extension)

> This is definitely a ghc bug, since Test.hs is not valid standard Haskell.
