### ISSUE TITLE
Parsing fails when source file uses pattern synonyms

### ISSUE THREAD

**Issue by eigengrau** [jaspervdj/stylish-haskell#82]
When pattern synonyms are used in a source file, running stylish-haskell will fail.

**Comment by mpickering** [comment]
This is a bug in HSE which will be fixed in the next version.

**Comment by neongreen** [comment]
I tried latest stylish-haskell on some random file which uses pattern synonyms: https://github.com/ocharles/blog/blob/master/code/2014-12-03-pattern-synonyms.hs – it seems to work. If you have an example which doesn't work, please open a new issue.
