### ISSUE TITLE
Typed holes not recognised

### ISSUE THREAD

**Issue by greenrd** [jaspervdj/stylish-haskell#83]
See https://wiki.haskell.org/GHC/Typed_holes

**Comment by greenrd** [comment]
Workaround: name the holes (e.g. _Foo) - stylish-haskell then assumes they are identifiers, I guess.

**Comment by jaspervdj** [comment]
This is really a `haskell-src-exts` issue, which is the library `stylish-haskell` uses to parse the code.

**Comment by greenrd** [comment]
Thanks. The issue is tracked here: https://github.com/haskell-suite/haskell-src-exts/issues/118
