### ISSUE TITLE
stylish-haskell doesn't understand shell shebang (#!) lines

### ISSUE THREAD

**Issue by radix** [jaspervdj/stylish-haskell#86]
When I run stylish-haskell on a file that starts with `#!/usr/bin/env runhaskell`, I get

```
Language.Haskell.Stylish.Parse.parseModule: could not parse src/Messin.hs: ParseFailed (SrcLoc "<unknown>.hs" 1 1) "Parse error: #!/"
```

I guess it should ignore the first line of a file if it begins with `#!`.

**Comment by jaspervdj** [comment]
Thanks for reporting!

**Comment by radix** [comment]
Awesome! Thank you very much, @jaspervdj! :cherry_blossom:
