### ISSUE TITLE
max line length (columns config option) is not being respected for certain imports

### ISSUE THREAD

**Issue by ababkin** [jaspervdj/stylish-haskell#87]
For example, the following line won't get rewritten to occupy 80 columns max, in fact it won't be changed at all.
But, even worse, if i split it up manually, stylish-haskell will join it again to form a line that is unnecessarily too long

I'm trying all of this with    `align: none`    config option

import XXXXXXXXXXXXXXXXXXXXXX.YYYYYYYYYYYYYY (Q (XXXXXXXXXXXXXX, YYYYYYYYYYYYYYYYYY, ZZZZZZZZZZZZZZZZZZZZZ), Z (AAAAAAAA, BBBBBBBBBBBB, CCCCCCCCCCCCCCCCCCCCC, DDDDDDDDDDDDDDDDDDDDDDD, EEEEEEEEEEEEEEEEEEEEEEEE, FFFFFFFFFFFFFFF))

**Comment by neongreen** [comment]
Duplicate of #35.
