### ISSUE TITLE
GHCJS foreign import support

### ISSUE THREAD

**Issue by geraldus** [jaspervdj/stylish-haskell#89]
Hi @jaspervdj ! 

Looks like `stylish-haskell` missing GHCJS foreign import support.  It looks like this:

```hs
foreign import javascript unsafe "$r = document;"
  js_document :: IO Elem

foreign import javascript unsafe "document.body"
  js_documentBody :: IO Elem

foreign import javascript unsafe
  "function ($1) { \
  \  while ($1.hasChildNodes()) \
  \    elem.removeChild($1.lastChild); \
  \}"
  js_clearChildren :: Elem -> IO ()
```

I've tried to enable `JavaScriptFFI` and `ForeignFunctionInterface` extensions, but this does not helped (though, the code itself compiles without these extensions).  It will be super cool to have such support.

**Comment by geraldus** [comment]
@jaspervdj if you can give some guidance how to make this possible I'll be happy to provide a PR.

**Comment by bergmark** [comment]
Everything parsing related needs to be implemented in haskell-src-exts.

**Comment by geraldus** [comment]
@bergmark thank you, I'll have a look.  By the way do you know is it same for HLint?

**Comment by bergmark** [comment]
Yep, it is.

**Comment by geraldus** [comment]
Ok! I've sent [pull request](https://github.com/haskell-suite/haskell-src-exts/pull/236) to **HSE** which brings GHCJS' foreign calling convention support, when it will be merged I'll send PR here (though I don't know how soon it will be merged).
