### ISSUE TITLE
Add stack.yaml

### ISSUE THREAD

**Issue by 3noch** [jaspervdj/stylish-haskell#95]
I just built `HEAD` with `stack` by running `stack init && stack build`. That means that your current config aligns perfectly with an existing LTS snapshot (currently 3.6). All you need to do is run `stack init` and then commit the resulting `stack.yaml` file. You might also want to add `.stack-work/` to `.gitignore`.

**Comment by jaspervdj** [comment]
While I do use stack to build applications for deployment, I typically don't use it for local development, so I don't really see the point -- it would just be another file to maintain, especially since `stylish-haskell` is already in Stackage.

**Comment by 3noch** [comment]
If there is a way to install binaries directly from Stackage (a la `stack install stylish-haskell`) then I'm sold. The main reason I want this is because IDEs use your amazing work to add styling capabilities. Having an easy way to install is especially helpful in getting those up and running. Unfortunately some systems are only running `stack` and don't even have `cabal` available.

**Comment by jaspervdj** [comment]
Well, if it helps adoption & installation for new users, I don't really have a problem with it. I was just a bit worried about the `resolver` field getting out of date.

**Comment by 3noch** [comment]
Thank you!

**Comment by 3noch** [comment]
I understand your concern about the `resolver` field.
